# Generated by Django 3.0.8 on 2020-07-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(max_length=20)),
                ('phone', models.IntegerField(max_length=10)),
                ('location', models.CharField(max_length=60)),
            ],
        ),
    ]
